DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Books;


create table Person(
    id int primary key generated by default as identity,
    username varchar(100) not null,
    year_of_birth int not null,
    password varchar not null,
    role varchar not null
);

insert into person(username, year_of_birth, password, role) values ('admin', 1960, '', 'ROLE_ADMIN');

CREATE TABLE Books (
                       id int primary key generated by default as identity,
                       name varchar(100) NOT NULL,
                       author varchar(100) NOT NULL,
                       year_release int4 NOT NULL
);

create table Orders(
                       id int primary key generated by default as identity,
                       person_id int not null,
                       book_id int not null,
                       status int not null,
                       date timestamp not null,
                       return_date timestamp,
                       CONSTRAINT orders_books_fk FOREIGN KEY (book_id) REFERENCES books(id)  ON DELETE CASCADE,
                       CONSTRAINT orders_person_fk FOREIGN KEY (person_id) REFERENCES person(id)  ON DELETE CASCADE
);


